name: Pull request on main or next

on:
  pull_request:
    branches: [ main, next ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      # Build before testing. Tests needs the api package to be built
      - run: npm run build
      - run: npm run bootstrap
      - run: npm run test
